name: Update Blog Index

on:
  push:
    paths:
      - "Blogs/*.html"
      - "generate-blog-index.js"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate blog index
        run: npm run build

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Blogs/blog-index.json
          git commit -m "Update blog index"
          git push
        continue-on-error: true
